### ISSUE TITLE
integrating with dagger-Hilt

### ISSUE THREAD

**Issue by EsmaeelNabil** [ahmedeltaher/MVVM-Kotlin-Android-Architecture#17]

**Comment by ahmedeltaher** [comment]
We will do.

**Comment by sagarkhakhar** [comment]
@ahmedeltaher buddy when can we get the new hilt integration repo? as you are doing awesome job thanks.

**Comment by ahmedeltaher** [comment]
> @ahmedeltaher buddy when can we get the ne

@sagarkhakhar, Done we have migrated from Dagger to Hilt.

**Comment by sagarkhakhar** [comment]
> > @ahmedeltaher buddy when can we get the ne
> 
> @sagarkhakhar, Done we have migrated from Dagger to Hilt.

@ahmedeltaher thanks buddy
