### ISSUE TITLE
AGPBI: {"kind":"error","text":"MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)","sources":[{}],"tool":"D8"}

### ISSUE THREAD

**Issue by CoolMind** [ahmedeltaher/MVVM-Kotlin-Android-Architecture#7]
Hello!
Yes, I know that can set min SDK = 26, but how to make it less? Java version 1.8 is already set.

**Comment by astraube** [comment]
Dear @CoolMind CoolMind friend, I also have this same problem. but in my case I need to keep minSdkVersion = 16. Could you solve the problem?

**Comment by astraube** [comment]
I found the problem, is the mockk that is crashing.

**Comment by EggEggs** [comment]
It seems to be a mockk related issue. 
I modified the mockk version to 1.9.2 so it was built normally.

**Comment by sagarkhakhar** [comment]
> It seems to be a mockk related issue.
> I modified the mockk version to 1.9.2 so it was built normally.

Thanks @astraube and @EggEggs after changing mockk version to 1.92. i was able to run the app on device thank you so much you saved me.

**Comment by ahmedeltaher** [comment]
Reverted to mockk version `1.9.2`, you can update from master

**Comment by sagarkhakhar** [comment]
Thanks @ahmedeltaher for your support for this architecture with all latest dependencies.

**Comment by CoolMind** [comment]
Thanks, @astraube, I am glad that you helped to solve the problem!
Also thanks to @EggEggs!
